name: C++ Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential cmake

    - name: Prepare build directory
      run: rm -rf build || true && mkdir build

    - name: Configure CMake
      run: cmake -S . -B build

    - name: Build
      run: cmake --build build
